### ISSUE TITLE
demo example don't work for me

### ISSUE THREAD

**Issue by elycheikhsmail** [astrodon/astrodon#41]
when run 
deno run -A --unstable https://deno.land/x/astrodon/examples/hello_world/demo.ts
I get 

```
ely@ely-ThinkPad-T450s:~$ deno run -A --unstable https://deno.land/x/astrodon/examples/hello_world/demo.ts
Download https://deno.land/x/astrodon/examples/hello_world/demo.ts
Warning Implicitly using latest version (0.1.0-alpha.2) for https://deno.land/x/astrodon/examples/hello_world/demo.ts
Download https://deno.land/x/astrodon/examples/hello_world/astrodon.config.ts
Warning Implicitly using latest version (0.1.0-alpha.2) for https://deno.land/x/astrodon/examples/hello_world/astrodon.config.ts
error: Uncaught (in promise) CacheError: /home/ely/superapp/astrodon/0.1.0-alpha.2/lib/libastrodon.so is not valid.
    throw new CacheError(`${path} is not valid.`);
          ^
    at protocolFile (https://deno.land/x/cache@0.2.13/file_fetcher.ts:12:11)
    at async fetchFile (https://deno.land/x/cache@0.2.13/file_fetcher.ts:41:14)
    at async FileWrapper.fetch (https://deno.land/x/cache@0.2.13/file.ts:95:18)
    at async FileWrapper.get (https://deno.land/x/cache@0.2.13/file.ts:113:12)
    at async cache (https://deno.land/x/cache@0.2.13/cache.ts:67:10)
    at async Wrapper.cache (https://deno.land/x/cache@0.2.13/cache.ts:21:12)
    at async download (https://deno.land/x/plug@0.5.1/plug.ts:96:16)
    at async Module.prepare (https://deno.land/x/plug@0.5.1/plug.ts:105:16)
    at async Function.new (https://deno.land/x/astrodon@0.1.0-alpha.2/modules/astrodon/mod.ts:115:21)
    at async https://deno.land/x/astrodon@0.1.0-alpha.2/examples/hello_world/demo.ts:18:13
ely@ely-ThinkPad-T450s:~$ 
```
I have ubuntu 20.04 as sytem
it seems there a pb for caching binary, I suggess to have to two command one for dowload and cach binary and the second for  create ui

**Comment by marc2332** [comment]
What Deno version do you have? Run `deno -V`

I am in Windows, and it works fine to me

**Comment by elycheikhsmail** [comment]
deno vrrsion 1.21.3 I will upgrade to latest versìon

**Comment by marc2332** [comment]
Try running with --reload if the error persists

**Comment by elycheikhsmail** [comment]
I upgrade deno to 1.22.0 then I delete the directory superapp then the astrodon demo work fine
thank you

**Comment by marc2332** [comment]
Awesome 🎉
